version: '3.8'

x-defaults: &defaults
  restart: always
  environment:
    - TZ=Asia/Taipei

services:
  grafana:
    <<: *defaults
    image: grafana/grafana:11.5.1
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - TZ=Asia/Taipei

  loki:
    <<: *defaults
    image: grafana/loki:3.4.2
    command:
      - '-config.file=/etc/loki/local-config.yaml'
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml

  tempo:
    <<: *defaults
    image: grafana/tempo:main-068b85c
    command:
      - '-config.file=/etc/tempo.yaml'
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml

  prometheus:
    <<: *defaults
    image: prom/prometheus:v3.1.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-otlp-receiver'

  otel-collector:
    <<: *defaults
    image: otel/opentelemetry-collector:0.119.0
    command:
      - '--config=/etc/otel-collector-config.yaml'
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
    depends_on:
      - prometheus
      - tempo
      - loki
